version: '3'
services:
  fare-calculation-service:
    image: fare-calculation-service
    container_name: fare-calculation-service
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/data:/data
    command: java -Xms512m -Xmx4g -jar app.jar '/data/paths.csv'